name: Foundation CI (v2)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Test Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: sudo apt-get install build-essential libsodium-dev libboost-system-dev
      - run: npm install
      - run: npm test
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Save Coverage Checks
        uses: actions/setup-node@v1
        with:
          node-version: 12.16
      - run: sudo apt-get install build-essential libsodium-dev libboost-system-dev
      - run: npm install && npm install -g codecov
      - run: npm run test && codecov
